### ISSUE TITLE
Add kernel config to repository

### ISSUE THREAD

**Issue by cookiengineer** [KonstaT/android_kernel_zte_msm8610#1]
Hey there,

I tried to build it, but no matter what I'm selecting, it always ends with an MSM_RPM_SMD selection of the msm8610 arch, which is not included in this kernel. How did you build it properly?

Cheers,
~CM

**Comment by KonstaT** [comment]
What branch are you using? kitkat-next is the one to currently use. kitkat-merge is highly experimental and merged all the way to the latest CAF tag.

Copy arch/arm/configs/msm8610-zte_defconfig as .config to the root of the kernel tree and compile with:
make ARCH=arm CROSS_COMPILE=path/to/android/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-

It compiles fine but I still don't have a device to test with. I've been waiting for the Kis 3 to be available but I'll probably still get the Open C (they're the same device). I guess you have an Open C? This source probably isn't suitable for building Firefox OS kernel which is Jelly Bean based. I specifically requested the Firefox OS kernel source from ZTE and they gave this instead. :P

BTW, I have a ClockWorkMod build if you/someone wants to test.

**Comment by cookiengineer** [comment]
Jep, I have a device. I'm trying out the kitkat-next branch and I'll give feedback if it worked. I was trying to port TWRP to the device with a working kernel for the ZTE Open C. I already installed the Chinese Android with full of spyware on my phone, but I haven't built my own yet.

The rootkit I'm also developing atm is here, but the root is only with the kernel, because the mounts are totally fucked up (like /storage/legacy, /data/data etc.):

https://github.com/martensms/zte-openc-rootkit

In order to port OmniROM, I need to get a recoverymod up and running again - the CWM builder is still down :( I was previously porting omniarmv6 to a couple old devices, that's why I'm experimenting with it.

Could you upload your CWM build somewhere? That would be nice!

Cheers,
~CM

**Comment by cookiengineer** [comment]
The paths for CROSS_COMPILE seem to have changed in the newest Android NDK release.
Also, there are some kernel mod mismatches. I got it now building with the new path to the bin folder:

``` bash
make ARCH=arm CROSS_COMPILE="~/Software/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/arm-linux-androideabi/bin/" CONFIG_NO_ERROR_ON_MISMATCH=y
```

**Comment by KonstaT** [comment]
I'm not using NDK. Just the regular AOSP toolchain that comes with any AOSP-based ROM's source code. KitKat still uses 4.7 toolchain.
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/

I'll send you some email tomorrow.
