### ISSUE TITLE
[Patch included ] Please hardening the kernel

### ISSUE THREAD

**Issue by theLOICofFRANCE** [KonstaT/android_kernel_zte_msm8610#3]
Hi,

I made the following changes on my smartphone:
1. Harden kernel config
2. Harden user_namespace
3. Port of grsecurity's deny_new_usb feature
4. Port of grsecurity's DEVICE_SIDECHANNEL feature
5. Add GRKERNSEC_PROC_IPADDR
6. proc: prevent accessing /proc/<PID>/environ until it's ready

See : [kernel_patch_for_lineage-UNOFFICIAL-kis3.txt](https://github.com/KonstaT/android_kernel_zte_msm8610/files/1364394/kernel_patch_for_lineage-UNOFFICIAL-kis3.txt)

I didn't have any problems with these changes. Thank you for your great work!

**Comment by KonstaT** [comment]
Rather open a pull request with original commit history.

I've retired my device so I won't be merging any changes anymore. I can leave you pull request open if anyone wants to pick it up.
